### ISSUE TITLE
Reminding players they are in a backup

### ISSUE THREAD

**Issue by xJon** [Silly511/Backups-Mod#23]
After receiving https://github.com/xJon/The-1.12.2-Pack/issues/216 I thought it might be a good idea to have players be reminded (maybe through chat?) every x minutes that they are in a backup in case they accidentally play inside it instead of restoring it into a new world.

**Comment by Fadenfire** [comment]
Yeah a lot of people have gotten confused with the enter backup not saving. There's a warning message that displays when you first enter a backup but it's easy to miss if lots of mods spam the chat. In version 1.5.4 I made it so that the message is displayed every five minutes so hopefully that'll help.

**Comment by xJon** [comment]
That's great, thank you!
