### ISSUE TITLE
Backup to single file

### ISSUE THREAD

**Issue by ocramc** [Silly511/Backups-Mod#33]
Rather than having every single file within the world folder gzipped, is there any way to configure a single tar being created which is then gzipped? Would make it more convenient for transferring backups remotely

**Comment by Fadenfire** [comment]
Each file is compressed individually so that files that haven't changed since the last backup can be hard linked to the previous backup. This mod is meant to create backups that are as small as possible, not to create backups that can be transferred and unpacked by other programs. If you want a mod that creates zip files then I suggest [FTB backup](https://www.curseforge.com/minecraft/mc-mods/ftb-backups).
