### ISSUE TITLE
Backup not saving after a few attempts

### ISSUE THREAD

**Issue by PleaseAnswerMe** [Silly511/Backups-Mod#35]
![image](https://user-images.githubusercontent.com/78056151/105922283-5b23a680-6008-11eb-80e6-51d614460e4b.png)

This problem can be temporarily solved by deleting the file called "Last" in the backupsmod folder. I wish for a more concrete solution that will fix this problem permanently.  In-game it will say:

Started Backup...
Backup Failed! Check log for more info. 

Can someone help me with this
Btw im pretty new to using github.

**Comment by Fadenfire** [comment]
Unfortunately, I don't think this has anything to do with my mod. Something is making it so that my mod can't write to that file. It could be another mod that you have, it could be a program on your computer, or something else entirely. My only suggestion is to try temporarily removing all of your other mods and see if that fixes it. If that doesn't work or you don't have any other mods installed then try reinstalling minecraft.
