### ISSUE TITLE
Command output broken

### ISSUE THREAD

**Issue by TheHalfPotato** [Silly511/Backups-Mod#40]
Command output seems broken.

Output looks like this when doing 
/bm restore
![image](https://user-images.githubusercontent.com/2426568/190755652-67d0f3ad-1fe3-4a2e-8649-fda1a1ee8a39.png)

/bm
![image](https://user-images.githubusercontent.com/2426568/190755835-88361721-fd66-416b-83e1-aa9dee250572.png)

Minecraft 1.12.2 Forge 14.23.5.2860
SpongeForge 7.4.7

**Comment by Fadenfire** [comment]
This is because you don't have the backups mod on your client. That is supposed to be localized text, but because you don't have to the backups mod on your client it just displays the localization key. Unfortunately there isn't really any good way to fix this due to the way that vanilla commands work. My best suggestion is to get the backups mod on your client.
